[platformio]
src_dir = src/esp32_sensor

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; Libraries used for RFID communication and MQTT protocol
lib_deps =
    miguelbalboa/MFRC522@^1.4.11
    knolleary/PubSubClient@^2.8
